import PreviewRenderer from "@/components/PreviewRenderer";
import { fetchProjectByShareSlug } from "@/lib/projects";
import { applyShareLinks } from "@/lib/shareLinks";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default async function SharePage({ params }: { params: { share_slug: string } }) {
  const project = await fetchProjectByShareSlug(params.share_slug);

  if (!project) {
    return (
      <div className="min-h-screen bg-primary text-[#F8FAFC] flex items-center justify-center">
        <p>Project not found.</p>
      </div>
    );
  }

  const expired = new Date(project.expires_at).getTime() < Date.now();
  if (expired) {
    return (
      <div className="min-h-screen bg-primary text-[#F8FAFC] flex items-center justify-center">
        <div className="surface-card rounded-[28px] p-8 text-center">
          <h1 className="text-2xl font-semibold">Link expired</h1>
          <p className="mt-2 text-sm text-muted">Create a new project to get a fresh link.</p>
          <a className="btn-primary mt-4 inline-flex px-4 py-2 text-sm font-semibold" href="/">
            Start a new project
          </a>
        </div>
      </div>
    );
  }

  const expiresAt = new Date(project.expires_at).toLocaleDateString("ka-GE", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const site = applyShareLinks(project.site, params.share_slug);

  return (
    <div className="min-h-screen bg-primary">
      <div className="border-b border-border bg-primary px-6 py-4 text-center text-sm text-muted">
        Generated by Weblive.ai (expires on {expiresAt}).
      </div>
      <div className="mx-auto max-w-6xl px-6 py-8">
        <PreviewRenderer site={site} />
      </div>
    </div>
  );
}
