import PreviewRenderer from "@/components/PreviewRenderer";
import { fetchProjectByShareSlug } from "@/lib/projects";
import { applyShareLinks } from "@/lib/shareLinks";

export const dynamic = "force-dynamic";
export const revalidate = 0;

function normalizePath(segments: string[]) {
  if (!segments || segments.length === 0) return "/";
  return `/${segments.join("/")}`;
}

function parseProductIndex(segments: string[]) {
  if (!segments || segments.length !== 2) return null;
  if (segments[0] !== "products") return null;
  const idx = Number(segments[1]);
  if (!Number.isFinite(idx) || idx < 1) return null;
  return idx - 1;
}

export default async function SharePagePath({
  params,
}: {
  params: { share_slug: string; page: string[] };
}) {
  const project = await fetchProjectByShareSlug(params.share_slug);

  if (!project) {
    return (
      <div className="min-h-screen bg-slate-950 text-white flex items-center justify-center">
        <p>Project not found.</p>
      </div>
    );
  }

  const expired = new Date(project.expires_at).getTime() < Date.now();
  if (expired) {
    return (
      <div className="min-h-screen bg-slate-950 text-white flex items-center justify-center">
        <div className="rounded-[28px] border border-white/10 bg-slate-900 p-8 text-center">
          <h1 className="text-2xl font-semibold">Link expired</h1>
          <p className="mt-2 text-sm text-white/70">Create a new project to get a fresh link.</p>
          <a className="mt-4 inline-flex rounded-full bg-white px-4 py-2 text-sm font-semibold text-slate-900" href="/">
            Start a new project
          </a>
        </div>
      </div>
    );
  }

  const slug = normalizePath(params.page);
  const productIndex = parseProductIndex(params.page);
  const site = applyShareLinks(project.site, params.share_slug);
  const page = site.pages.find((p: any) => p.slug === slug) || site.pages[0];
  const products = project.input.products || [];
  const activeProduct = productIndex !== null ? products[productIndex] : null;
  const otherProducts =
    productIndex !== null
      ? products
          .map((product: any, idx: number) => ({ product, idx }))
          .filter((item: any) => item.idx !== productIndex)
      : [];

  const expiresAt = new Date(project.expires_at).toLocaleDateString("ka-GE", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="min-h-screen bg-slate-50">
      <div className="border-b border-slate-200 bg-white/80 px-6 py-4 text-center text-sm text-slate-600">
        Generated by Weblive.ai (expires on {expiresAt}).
      </div>
      <div className="mx-auto max-w-6xl px-6 py-8">
        {activeProduct ? (
          <div className="space-y-10">
            <section className="rounded-2xl bg-white p-8 shadow-sm">
              <div className="grid gap-8 md:grid-cols-2">
                <div className="overflow-hidden rounded-xl bg-slate-100">
                  <img
                    src={activeProduct.imageUrl || "/placeholders/scene-2.svg"}
                    alt={activeProduct.name}
                    className="h-full w-full object-cover"
                  />
                </div>
                <div className="space-y-4">
                  <h1 className="text-3xl font-semibold text-slate-900">{activeProduct.name}</h1>
                  <p className="text-2xl font-semibold text-slate-700">{activeProduct.price}</p>
                  <a
                    href={`tel:${project.input.contact?.phone || ""}`}
                    className="inline-flex rounded-lg bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white"
                  >
                    Contact Us
                  </a>
                </div>
              </div>
            </section>

            {otherProducts.length > 0 && (
              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-slate-900">Other Products</h2>
                <div className={`grid gap-6 ${otherProducts.length === 1 ? "md:grid-cols-1" : otherProducts.length === 2 ? "md:grid-cols-2" : "md:grid-cols-3"}`}>
                  {otherProducts.map((item: any, idx: number) => {
                    const product = item.product;
                    const href = `/s/${params.share_slug}/products/${item.idx + 1}`;
                    return (
                      <article key={`${product.name}-${idx}`} className="overflow-hidden rounded-xl bg-white shadow-sm">
                        <div className="aspect-[4/3] overflow-hidden bg-slate-100">
                          <img
                            src={product.imageUrl || "/placeholders/scene-2.svg"}
                            alt={product.name}
                            className="h-full w-full object-cover"
                          />
                        </div>
                        <div className="space-y-2 p-4">
                          <h3 className="text-lg font-semibold text-slate-900">{product.name}</h3>
                          <p className="text-base font-medium text-slate-700">{product.price}</p>
                          <a href={href} className="inline-flex rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-900">
                            View Details
                          </a>
                        </div>
                      </article>
                    );
                  })}
                </div>
              </section>
            )}
          </div>
        ) : (
          <PreviewRenderer site={site} pageId={page.id} />
        )}
      </div>
    </div>
  );
}
